name: CI/Prettier

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Run Prettier
        run: bun run format
      - name: Check whether files were not formatted
        run: |
          if ! git diff --exit-code; then
            echo "Files were not formatted. Please run 'bun run format' and commit the changes."
            exit 1
          fi
